[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.121.1"
NODE_VERSION = "20.11.1"
GO_VERSION = "1.21.6"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"