[build]
publish = "public"
command = "npm i -g postcss-cli && npm run build"

[build.environment]
HUGO_VERSION = "0.121.1"
NODE_VERSION = "20.11.1"
NPM_VERSION = "10.2.4"

[context.production.environment]
HUGO_ENV = "production"